name: test
title: test
description: test
body:
  - type: textarea
    id: queries
    attributes:
      label: SQL
      description: Enter the DML query. Input Google Drive URL on here if DML query includes PII (Personal Identification Information)
      placeholder: INSERT INTO main ...
      render: SQL
    validations:
      required: true
