name: test
title: test
description: test
body:
  - type: textarea
    id: queries
    attributes:
      label: hoge
      placeholder: INSERT INTO main ...
      render: SQL
    validations:
      required: true
